export const STUDENTADD_REQUEST = "STUDENTADD_REQUEST"
export const STUDENTADD_SUCCESS = "STUDENTADD_SUCCESS"
export const STUDENTADD_FAILURE = "STUDENTADD_FAILURE"
export const STUDENTGET_REQUEST = "STUDENTGET_REQUEST"
export const STUDENTGET_SUCCESS = "STUDENTGET_SUCCESS"
export const STUDENTGET_FAILURE = "STUDENTGET_FAILURE"
export const STUDENTDELETE_REQUEST = "STUDENTDELETE_REQUEST"
export const STUDENTDELETE_SUCCESS = "STUDENTDELETE_SUCCESS"
export const STUDENTDELETE_FAILURE = "STUDENTDELETE_FAILURE"
export const STUDENTUPDATE_REQUEST = "STUDENTUPDATE_REQUEST"
export const STUDENTUPDATE_SUCCESS = "STUDENTUPDATE_SUCCESS"
export const STUDENTUPDATE_FAILURE = "STUDENTUPDATE_FAILURE"




